task: token_classification

model:
    model_id: BASE_DIR/expts/conll2003_classification/final_model
    tokenizer_id: BASE_DIR/expts/conll2003_classification/final_model

hyperparams:
    batch_size: 16

processing:
    output_dir: BASE_DIR/expts/conll2003_classification
    seed: 42

data:
    inference_jsonl: BASE_DIR/data/conll2003/inference.jsonl
