task: instruction_ft

model:
    model_id: BASE_DIR/expts/alpaca_instruction_ft
    tokenizer_id: BASE_DIR/expts/alpaca_instruction_ft

hyperparams:
    per_device_eval_batch_size: 16
    max_seq_length: 512

processing:
    output_dir: BASE_DIR/expts/alpaca_instruction_ft
    seed: 42

