task: dpo_ft

model:
    model_id: BASE_DIR/expts/ultrafeedback_dpo
    tokenizer_id: BASE_DIR/expts/ultrafeedback_dpo

hyperparams:
    per_device_eval_batch_size: 8
    max_seq_length: 1024

lora:
    r: 16
    alpha: 16
    target_modules:
        - q_proj
        - k_proj
        - v_proj
        - o_proj
    task_type: CAUSAL_LM

processing:
    output_dir: BASE_DIR/expts/ultrafeedback_dpo
    seed: 42

