task: sequence_classification

model:
    model_id: BASE_DIR/expts/emotion_classification/final_model
    tokenizer_id: BASE_DIR/expts/emotion_classification/final_model

hyperparams:
    batch_size: 16

processing:
    output_dir: BASE_DIR/expts/emotion_classification
    seed: 42

data:
    test_jsonl: BASE_DIR/data/emotion/test.jsonl
