task: sequence_classification

model:
    model_id: BASE_DIR/expts/emotion_classification/final_model
    tokenizer_id: BASE_DIR/expts/emotion_classification/final_model

hyperparams:
    batch_size: 16

data:
    inference_jsonl: BASE_DIR/data/emotion/inference.jsonl
