task: custom_sequence_classification

model:
    model_id: bert-base-uncased
    tokenizer_id: bert-base-uncased
    model_path: BASE_DIR/expts/restaurant_category

hyperparams:
    batch_size: 16
    max_seq_length: 512

processing:
    output_dir: BASE_DIR/expts/restaurant_category
    seed: 42

data:
    test_jsonl: BASE_DIR/data/restaurant/validation.jsonl
