task: spanpair_classification

model:
    model_id: microsoft/deberta-v3-base
    tokenizer_id: microsoft/deberta-v3-base

hyperparams:
    batch_size: 16
    gradient_accumulation_steps: 1
    epoch: 3
    learning_rate: 0.00001
    warmup_steps: 0
    save_steps: 10000
    save_total_limit: 0
    encoder_dropout: 0
    linear_dropout: 0
    fcl_hidden_dim: 600
    max_seq_length: 256

processing:
    output_dir: BASE_DIR/expts/nyth_classification
    seed: 42

data:
    train_jsonl: BASE_DIR/data/nyth/train_nonna.sampled.jsonl
    validation_jsonl: BASE_DIR/data/nyth/dev.jsonl
