task: spanpair_classification

model:
    model_id: microsoft/deberta-v3-base
    tokenizer_id: BASE_DIR/expts/nyth_classification
    model_path: BASE_DIR/expts/nyth_classification

hyperparams:
    batch_size: 16
    encoder_dropout: 0
    linear_dropout: 0
    fcl_hidden_dim: 600
    max_seq_length: 256

processing:
    output_dir: BASE_DIR/expts/nyth_classification
    seed: 42

data:
    test_jsonl: BASE_DIR/data/nyth/dev.jsonl
