task: triplet_contrastive_learning

model:
    model_id: microsoft/deberta-v3-base
    tokenizer_id: microsoft/deberta-v3-base

hyperparams:
    batch_size: 16
    gradient_accumulation_steps: 1
    epoch: 3
    learning_rate: 0.000005
    warmup_steps: 0
    save_steps: 10000
    save_total_limit: 0
    temperature: 1.0
    max_seq_length: 128

processing:
    output_dir: BASE_DIR/expts/bioasq_triplet_contrastive
    seed: 42

data:
    train_jsonl: BASE_DIR/data/bioasq/train.jsonl
    validation_jsonl: BASE_DIR/data/bioasq/validation.jsonl
